spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/webmall?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
#    指明数据库相关包和类的位置和配置信息
mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: org.example.pojo